/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerOption { 'id' : string, 'text' : string }
export type BodyRegion = { 'back' : null } |
  { 'head' : null } |
  { 'chest' : null } |
  { 'skin' : null } |
  { 'limbs' : null } |
  { 'throat' : null } |
  { 'general' : null } |
  { 'abdomen' : null };
export interface Condition {
  'id' : ConditionId,
  'name' : string,
  'triageLevel' : TriageLevel,
  'description' : string,
  'confidenceScore' : bigint,
  'whenToSeeDoctor' : string,
}
export type ConditionId = bigint;
export interface FollowUpQuestion {
  'id' : QuestionId,
  'answerOptions' : Array<AnswerOption>,
  'symptomId' : SymptomId,
  'questionText' : string,
}
export type QuestionId = bigint;
export interface Symptom {
  'id' : SymptomId,
  'bodyRegion' : BodyRegion,
  'name' : string,
  'description' : string,
}
export interface SymptomAnswer {
  'answerId' : string,
  'questionId' : QuestionId,
}
export type SymptomId = bigint;
export type TriageLevel = { 'er' : null } |
  { 'urgentCare' : null } |
  { 'selfCare' : null } |
  { 'telehealth' : null };
export interface _SERVICE {
  'analyzeSymptoms' : ActorMethod<
    [Array<SymptomId>, Array<SymptomAnswer>],
    Array<Condition>
  >,
  'getFollowUpQuestions' : ActorMethod<
    [Array<SymptomId>],
    Array<FollowUpQuestion>
  >,
  'getSymptoms' : ActorMethod<[], Array<Symptom>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];