/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SymptomId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const SymptomAnswer = IDL.Record({
  'answerId' : IDL.Text,
  'questionId' : QuestionId,
});
export const ConditionId = IDL.Nat;
export const TriageLevel = IDL.Variant({
  'er' : IDL.Null,
  'urgentCare' : IDL.Null,
  'selfCare' : IDL.Null,
  'telehealth' : IDL.Null,
});
export const Condition = IDL.Record({
  'id' : ConditionId,
  'name' : IDL.Text,
  'triageLevel' : TriageLevel,
  'description' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'whenToSeeDoctor' : IDL.Text,
});
export const AnswerOption = IDL.Record({ 'id' : IDL.Text, 'text' : IDL.Text });
export const FollowUpQuestion = IDL.Record({
  'id' : QuestionId,
  'answerOptions' : IDL.Vec(AnswerOption),
  'symptomId' : SymptomId,
  'questionText' : IDL.Text,
});
export const BodyRegion = IDL.Variant({
  'back' : IDL.Null,
  'head' : IDL.Null,
  'chest' : IDL.Null,
  'skin' : IDL.Null,
  'limbs' : IDL.Null,
  'throat' : IDL.Null,
  'general' : IDL.Null,
  'abdomen' : IDL.Null,
});
export const Symptom = IDL.Record({
  'id' : SymptomId,
  'bodyRegion' : BodyRegion,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'analyzeSymptoms' : IDL.Func(
      [IDL.Vec(SymptomId), IDL.Vec(SymptomAnswer)],
      [IDL.Vec(Condition)],
      ['query'],
    ),
  'getFollowUpQuestions' : IDL.Func(
      [IDL.Vec(SymptomId)],
      [IDL.Vec(FollowUpQuestion)],
      ['query'],
    ),
  'getSymptoms' : IDL.Func([], [IDL.Vec(Symptom)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SymptomId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const SymptomAnswer = IDL.Record({
    'answerId' : IDL.Text,
    'questionId' : QuestionId,
  });
  const ConditionId = IDL.Nat;
  const TriageLevel = IDL.Variant({
    'er' : IDL.Null,
    'urgentCare' : IDL.Null,
    'selfCare' : IDL.Null,
    'telehealth' : IDL.Null,
  });
  const Condition = IDL.Record({
    'id' : ConditionId,
    'name' : IDL.Text,
    'triageLevel' : TriageLevel,
    'description' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'whenToSeeDoctor' : IDL.Text,
  });
  const AnswerOption = IDL.Record({ 'id' : IDL.Text, 'text' : IDL.Text });
  const FollowUpQuestion = IDL.Record({
    'id' : QuestionId,
    'answerOptions' : IDL.Vec(AnswerOption),
    'symptomId' : SymptomId,
    'questionText' : IDL.Text,
  });
  const BodyRegion = IDL.Variant({
    'back' : IDL.Null,
    'head' : IDL.Null,
    'chest' : IDL.Null,
    'skin' : IDL.Null,
    'limbs' : IDL.Null,
    'throat' : IDL.Null,
    'general' : IDL.Null,
    'abdomen' : IDL.Null,
  });
  const Symptom = IDL.Record({
    'id' : SymptomId,
    'bodyRegion' : BodyRegion,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'analyzeSymptoms' : IDL.Func(
        [IDL.Vec(SymptomId), IDL.Vec(SymptomAnswer)],
        [IDL.Vec(Condition)],
        ['query'],
      ),
    'getFollowUpQuestions' : IDL.Func(
        [IDL.Vec(SymptomId)],
        [IDL.Vec(FollowUpQuestion)],
        ['query'],
      ),
    'getSymptoms' : IDL.Func([], [IDL.Vec(Symptom)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };