/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SymptomAnswer {
    answerId: string;
    questionId: QuestionId;
}
export type ConditionId = bigint;
export interface Condition {
    id: ConditionId;
    name: string;
    triageLevel: TriageLevel;
    description: string;
    confidenceScore: bigint;
    whenToSeeDoctor: string;
}
export type SymptomId = bigint;
export type QuestionId = bigint;
export interface FollowUpQuestion {
    id: QuestionId;
    answerOptions: Array<AnswerOption>;
    symptomId: SymptomId;
    questionText: string;
}
export interface Symptom {
    id: SymptomId;
    bodyRegion: BodyRegion;
    name: string;
    description: string;
}
export interface AnswerOption {
    id: string;
    text: string;
}
export enum BodyRegion {
    back = "back",
    head = "head",
    chest = "chest",
    skin = "skin",
    limbs = "limbs",
    throat = "throat",
    general = "general",
    abdomen = "abdomen"
}
export enum TriageLevel {
    er = "er",
    urgentCare = "urgentCare",
    selfCare = "selfCare",
    telehealth = "telehealth"
}
export interface backendInterface {
    analyzeSymptoms(symptomIds: Array<SymptomId>, answers: Array<SymptomAnswer>): Promise<Array<Condition>>;
    getFollowUpQuestions(symptomIds: Array<SymptomId>): Promise<Array<FollowUpQuestion>>;
    getSymptoms(): Promise<Array<Symptom>>;
}
import type { BodyRegion as _BodyRegion, Condition as _Condition, ConditionId as _ConditionId, Symptom as _Symptom, SymptomId as _SymptomId, TriageLevel as _TriageLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeSymptoms(arg0: Array<SymptomId>, arg1: Array<SymptomAnswer>): Promise<Array<Condition>> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeSymptoms(arg0, arg1);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeSymptoms(arg0, arg1);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowUpQuestions(arg0: Array<SymptomId>): Promise<Array<FollowUpQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUpQuestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUpQuestions(arg0);
            return result;
        }
    }
    async getSymptoms(): Promise<Array<Symptom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSymptoms();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSymptoms();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BodyRegion_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyRegion): BodyRegion {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Condition_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Condition): Condition {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Symptom_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Symptom): Symptom {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TriageLevel_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TriageLevel): TriageLevel {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConditionId;
    name: string;
    triageLevel: _TriageLevel;
    description: string;
    confidenceScore: bigint;
    whenToSeeDoctor: string;
}): {
    id: ConditionId;
    name: string;
    triageLevel: TriageLevel;
    description: string;
    confidenceScore: bigint;
    whenToSeeDoctor: string;
} {
    return {
        id: value.id,
        name: value.name,
        triageLevel: from_candid_TriageLevel_n4(_uploadFile, _downloadFile, value.triageLevel),
        description: value.description,
        confidenceScore: value.confidenceScore,
        whenToSeeDoctor: value.whenToSeeDoctor
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SymptomId;
    bodyRegion: _BodyRegion;
    name: string;
    description: string;
}): {
    id: SymptomId;
    bodyRegion: BodyRegion;
    name: string;
    description: string;
} {
    return {
        id: value.id,
        bodyRegion: from_candid_BodyRegion_n9(_uploadFile, _downloadFile, value.bodyRegion),
        name: value.name,
        description: value.description
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    back: null;
} | {
    head: null;
} | {
    chest: null;
} | {
    skin: null;
} | {
    limbs: null;
} | {
    throat: null;
} | {
    general: null;
} | {
    abdomen: null;
}): BodyRegion {
    return "back" in value ? BodyRegion.back : "head" in value ? BodyRegion.head : "chest" in value ? BodyRegion.chest : "skin" in value ? BodyRegion.skin : "limbs" in value ? BodyRegion.limbs : "throat" in value ? BodyRegion.throat : "general" in value ? BodyRegion.general : "abdomen" in value ? BodyRegion.abdomen : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    er: null;
} | {
    urgentCare: null;
} | {
    selfCare: null;
} | {
    telehealth: null;
}): TriageLevel {
    return "er" in value ? TriageLevel.er : "urgentCare" in value ? TriageLevel.urgentCare : "selfCare" in value ? TriageLevel.selfCare : "telehealth" in value ? TriageLevel.telehealth : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Condition>): Array<Condition> {
    return value.map((x)=>from_candid_Condition_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Symptom>): Array<Symptom> {
    return value.map((x)=>from_candid_Symptom_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
